language: objective-c
osx_image: xcode7
branches:
  only:
    - master
before_install:
  - export LANG=en_US.UTF-8
  - brew update
install:
  - cd DemoSwift && pod install && cd ..
  - cd DemoObjC && pod install && cd ..
script:
  - xctool -configuration Debug -sdk iphonesimulator -workspace DemoSwift/Demo.xcworkspace -scheme Demo build-tests
  - xctool -workspace DemoSwift/Demo.xcworkspace -scheme Demo run-tests -test-sdk iphonesimulator9.0
  - xctool -configuration Debug -sdk iphonesimulator -workspace DemoObjC/Demo.xcworkspace -scheme Demo build-tests
  - xctool -workspace DemoObjC/Demo.xcworkspace -scheme Demo run-tests -test-sdk iphonesimulator9.0
