language: objective-c
osx_image: xcode7
branches:
  only:
    - master
before_install:
  - export LANG=en_US.UTF-8
  - brew update
install:
  - cd SwiftTests && pod install && cd ..
  - cd ObjCTests && pod install && cd ..
script:
  - xctool -sdk iphonesimulator -workspace SwiftTests/SwiftTests.xcworkspace -scheme Tests clean build-tests run-tests
  - xctool -configuration Debug -sdk iphonesimulator -workspace ObjCTests/ObjCTests.xcworkspace -scheme Tests build-tests
  - xctool -workspace ObjCTests/ObjCTests.xcworkspace -scheme Tests run-tests -test-sdk iphonesimulator9.0
