language: objective-c
osx_image: beta-xcode6.3
branches:
  only:
    - master
before_script:
  - "cd Demo && pod install && cd .."
script:
  - "xctool test -project Demo/Demo.xcodeproj -scheme DemoTests -sdk iphonesimulator"
