language: objective-c
osx_image: xcode63
before_install: 
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
script:
  - xctool test -project test/MEViewExtensions.xcodeproj -scheme MEViewExtensionsTests -sdk iphonesimulator8.3
