language: objective-c
osx_image: xcode7
branches:
  only:
    - master
before_install:
  - export LANG=en_US.UTF-8
  - brew update
  - gem install specific_install
  - gem specific_install -l https://github.com/venmo/slather.git
install:
  - cd SwiftTests && pod install && cd ..
  - cd ObjCTests && pod install && cd ..
after_success:
  - cd $TRAVIS_BUILD_DIR && slather
env:
  - TEST_SUITE=SwiftTests
  - TEST_SUITE=ObjCTests
script:
  - xctool
    -workspace ${TEST_SUITE}/${TEST_SUITE}.xcworkspace
    -scheme Tests
    -sdk iphonesimulator9.0
    clean build-tests run-tests
